// ---------------------------------------------------------------------------
// SpeakUp configuration
// ---------------------------------------------------------------------------
// Everything you may want to change lives here.

export const CONFIG = {
	// ---- Supabase -----------------------------------------------------------
	// The publishable (anon) key is meant to live in the browser. Never put a
	// service-role key or a personal access token (sbp_...) in this file.
	supabase: {
		url: "https://qzjmmbgazaweqtbwpmuh.supabase.co",
		anonKey: "sb_publishable_V6fyWf2c3hAG2yo0EcKw9g_U0qR507_",
		// When Supabase is unreachable (or the tables are not created yet) the app
		// keeps working and saves progress in localStorage instead.
		fallbackToLocal: true,
	},

	// ---- AI (Puter, user-pays: costs the developer nothing) ------------------
	ai: {
		// Tried in order until one answers.
		transcribeModels: ["gpt-4o-mini-transcribe", "whisper-1"],
		chatModels: ["gpt-5-nano", "gpt-4o-mini", "claude-sonnet-4"],
		// Topics are generated by AI once and then cached, so opening the app is instant.
		topicCacheSize: 40,
	},

	// ---- Practice rules -----------------------------------------------------
	rules: {
		minSecondsForCredit: 20, // a day only counts once you finish a recording this long
		minSecondsToCheck: 5, // below this we refuse to send it for checking
		maxSeconds: 180, // recording stops itself here
		streakGraceDays: 0, // 0 = hard reset at midnight, 1 = one day off allowed
		heatmapWeeks: 52,
		heatmapWeeksCompact: 20,
	},
};

export const REMARKS = [
	{ key: "very bad", cls: "r-verybad", min: 0 },
	{ key: "bad", cls: "r-bad", min: 3 },
	{ key: "good", cls: "r-good", min: 5 },
	{ key: "very good", cls: "r-verygood", min: 7 },
	{ key: "excellent", cls: "r-excellent", min: 9 },
];

export function remarkForScore(score) {
	let out = REMARKS[0];
	for (const r of REMARKS) if (score >= r.min) out = r;
	return out;
}

export function remarkClass(remark) {
	const found = REMARKS.find((r) => r.key === String(remark || "").toLowerCase().trim());
	return found ? found.cls : "r-good";
}
