-- ===========================================================================
-- SpeakUp — Supabase schema
-- Run this once in Supabase Dashboard -> SQL Editor -> New query -> Run.
-- Safe to run again; everything is IF NOT EXISTS / idempotent.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Topics
-- ---------------------------------------------------------------------------
create table if not exists public.topics (
  id          bigint generated by default as identity primary key,
  level       text not null default 'medium' check (level in ('easy','medium','hard')),
  text        text not null unique,
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2. Sessions (one finished practice attempt)
-- ---------------------------------------------------------------------------
create table if not exists public.sessions (
  id               uuid primary key default gen_random_uuid(),
  puter_user_id    text not null,
  topic_text       text not null,
  topic_level      text,
  transcript       text,
  duration_seconds integer not null default 0,
  word_count       integer not null default 0,
  score            smallint check (score between 0 and 10),
  accuracy         smallint check (accuracy between 0 and 10),
  complexity       smallint check (complexity between 0 and 10),
  remark           text check (remark in ('very bad','bad','good','very good','excellent')),
  level_note       text,
  report           jsonb,            -- full marked-up report, so old sessions can be reopened
  local_day        date not null,    -- the user's own calendar day (streaks)
  created_at       timestamptz not null default now()
);

create index if not exists sessions_user_created_idx on public.sessions (puter_user_id, created_at desc);
create index if not exists sessions_user_day_idx     on public.sessions (puter_user_id, local_day);

-- ---------------------------------------------------------------------------
-- 3. Daily attendance (drives the GitHub-style grid)
-- ---------------------------------------------------------------------------
create table if not exists public.daily_activity (
  puter_user_id text not null,
  local_day     date not null,
  sessions      integer not null default 0,
  best_score    smallint not null default 0,
  updated_at    timestamptz not null default now(),
  primary key (puter_user_id, local_day)
);

-- ---------------------------------------------------------------------------
-- 4. Mark a day present (called once per credited session)
-- ---------------------------------------------------------------------------
create or replace function public.speakup_mark_day(p_user text, p_day date, p_score smallint)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.daily_activity (puter_user_id, local_day, sessions, best_score, updated_at)
  values (p_user, p_day, 1, coalesce(p_score, 0), now())
  on conflict (puter_user_id, local_day) do update
    set sessions   = public.daily_activity.sessions + 1,
        best_score = greatest(public.daily_activity.best_score, coalesce(excluded.best_score, 0)),
        updated_at = now();
$$;

-- Accept an int argument too, since PostgREST may send a plain integer.
create or replace function public.speakup_mark_day(p_user text, p_day date, p_score integer)
returns void
language sql
security definer
set search_path = public
as $$
  select public.speakup_mark_day(p_user, p_day, p_score::smallint);
$$;

-- ---------------------------------------------------------------------------
-- 5. Handy read-only view of streak inputs
-- ---------------------------------------------------------------------------
create or replace view public.speakup_user_stats as
select puter_user_id,
       count(*)                       as active_days,
       sum(sessions)                  as total_sessions,
       round(avg(best_score)::numeric, 1) as avg_best_score,
       max(local_day)                 as last_day
from public.daily_activity
group by puter_user_id;

-- ---------------------------------------------------------------------------
-- 6. Row level security
-- ---------------------------------------------------------------------------
-- NOTE ON THE SECURITY MODEL
-- Sign-in is handled by Puter, not Supabase Auth, so there is no auth.uid()
-- to match against. For v1 the anon (publishable) key is allowed to insert and
-- read rows scoped by puter_user_id. That is fine for a practice app: the data
-- is not sensitive and a user can only see rows they ask for. It is NOT
-- tamper-proof — a determined person could read another id's sessions or fake
-- a streak.
-- When you want that closed off, see README "Locking it down": move writes into
-- an Edge Function that verifies the Puter token, then replace the policies
-- below with `using (false)` for anon.

alter table public.topics         enable row level security;
alter table public.sessions       enable row level security;
alter table public.daily_activity enable row level security;

drop policy if exists topics_read on public.topics;
create policy topics_read on public.topics
  for select to anon, authenticated using (true);

drop policy if exists sessions_read on public.sessions;
create policy sessions_read on public.sessions
  for select to anon, authenticated using (true);

drop policy if exists sessions_insert on public.sessions;
create policy sessions_insert on public.sessions
  for insert to anon, authenticated with check (puter_user_id is not null and length(puter_user_id) between 1 and 128);

drop policy if exists activity_read on public.daily_activity;
create policy activity_read on public.daily_activity
  for select to anon, authenticated using (true);

-- writes to daily_activity only happen through speakup_mark_day (security definer)
revoke insert, update, delete on public.daily_activity from anon, authenticated;
grant execute on function public.speakup_mark_day(text, date, smallint) to anon, authenticated;
grant execute on function public.speakup_mark_day(text, date, integer)  to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 7. Seed topics
-- ---------------------------------------------------------------------------
insert into public.topics (level, text) values
  ('easy','Describe your morning today, from waking up until now.'),
  ('easy','Talk about a meal you love and who usually cooks it.'),
  ('easy','Describe the street where you live.'),
  ('easy','Tell me about a friend and how you met.'),
  ('easy','What do you usually do on a day off?'),
  ('easy','Describe the weather this week and how it changed your plans.'),
  ('easy','Talk about a shop or market you go to often.'),
  ('easy','Describe your phone and the three apps you open most.'),
  ('easy','Tell me about a song you keep playing.'),
  ('easy','What did you eat yesterday, and was it good?'),
  ('easy','Describe someone in your family in detail.'),
  ('easy','Talk about how you travel to work or school.'),
  ('easy','Describe a photo on your phone that you like.'),
  ('easy','What is your favourite time of day, and why?'),
  ('medium','Tell me about a time you were completely lost.'),
  ('medium','Describe a mistake that taught you something useful.'),
  ('medium','Explain your work or studies to someone who knows nothing about it.'),
  ('medium','Talk about a habit you are trying to build, and how it is going.'),
  ('medium','Describe the best trip you have taken and what surprised you.'),
  ('medium','Explain how to cook something, step by step.'),
  ('medium','Talk about a film or show you would recommend, without spoiling it.'),
  ('medium','Describe a person who changed how you think.'),
  ('medium','Tell me about a time you had to say no to someone.'),
  ('medium','What would you change about your city if you were the mayor?'),
  ('medium','Describe something you bought that was not worth the money.'),
  ('medium','Talk about a skill you want to learn this year and your plan for it.'),
  ('medium','Explain a piece of news you read recently and what you think about it.'),
  ('medium','Describe a time you helped someone you did not know.'),
  ('hard','Should social media have an age limit? Argue one side.'),
  ('hard','Is it better to be respected or to be liked? Explain your reasoning.'),
  ('hard','Describe a problem in your industry and how you would fix it.'),
  ('hard','Will AI make people lazier or sharper? Defend your view.'),
  ('hard','Explain a decision you regret, and what you would tell your past self.'),
  ('hard','Should university be free for everyone? Give reasons and an example.'),
  ('hard','Talk about a belief you held strongly and later dropped.'),
  ('hard','Is remote work good for young people starting a career?'),
  ('hard','Describe how money changes friendships.'),
  ('hard','If you had to lead a team tomorrow, how would you start?'),
  ('hard','What responsibility do rich countries have for climate change?'),
  ('hard','Explain something you believe most people around you get wrong.')
on conflict (text) do nothing;
